<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Enums\OrderStatus;
use App\Enums\PaymentStatus;

class OrdersTableSeeder extends Seeder
{
    public function run()
    {
        $orders = [
            [
                'user_id'           => 1,
                'promotion_id'      => 1,
                'total_amount'      => 100.00,
                'discount_amount'   => 20.00,
                'status'            => OrderStatus::PROCESSING,
                'payment_status'    => PaymentStatus::PENDING,
                'shipping_address'  => '123 Main St, Anytown, USA',
                'payment_method_id' => 1,
                'phone_number'      => '0123456789',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'user_id'           => 2,
                'promotion_id'      => 2,
                'total_amount'      => 200.00,
                'discount_amount'   => 30.00,
                'status'            => OrderStatus::PROCESSING,
                'payment_status'    => PaymentStatus::PENDING,
                'shipping_address'  => '456 Elm St, Othertown, USA',
                'payment_method_id' => 2,
                'phone_number'      => '0987654321',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'user_id'           => 3,
                'promotion_id'      => 3,
                'total_amount'      => 150.00,
                'discount_amount'   => 15.00,
                'status'            => OrderStatus::PROCESSING,
                'payment_status'    => PaymentStatus::PENDING,
                'shipping_address'  => '789 Pine St, Newtown, USA',
                'payment_method_id' => 1,
                'phone_number'      => '0112233445',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'user_id'           => 1,
                'promotion_id'      => 1,
                'total_amount'      => 120.00,
                'discount_amount'   => 25.00,
                'status'            => OrderStatus::PROCESSING,
                'payment_status'    => PaymentStatus::PENDING,
                'shipping_address'  => '321 Oak St, Anytown, USA',
                'payment_method_id' => 2,
                'phone_number'      => '0156784321',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'user_id'           => 2,
                'promotion_id'      => 2,
                'total_amount'      => 300.00,
                'discount_amount'   => 50.00,
                'status'            => OrderStatus::PROCESSING,
                'payment_status'    => PaymentStatus::PENDING,
                'shipping_address'  => '654 Maple St, Othertown, USA',
                'payment_method_id' => 1,
                'phone_number'      => '0198765432',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'user_id'           => 3,
                'promotion_id'      => 3,
                'total_amount'      => 400.00,
                'discount_amount'   => 60.00,
                'status'            => OrderStatus::PROCESSING,
                'payment_status'    => PaymentStatus::PENDING,
                'shipping_address'  => '987 Cedar St, Newtown, USA',
                'payment_method_id' => 2,
                'phone_number'      => '0187654321',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'user_id'           => 1,
                'promotion_id'      => 2,
                'total_amount'      => 220.00,
                'discount_amount'   => 40.00,
                'status'            => OrderStatus::PROCESSING,
                'payment_status'    => PaymentStatus::PENDING,
                'shipping_address'  => '159 Birch St, Anytown, USA',
                'payment_method_id' => 1,
                'phone_number'      => '0123456788',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'user_id'           => 2,
                'promotion_id'      => 1,
                'total_amount'      => 180.00,
                'discount_amount'   => 20.00,
                'status'            => OrderStatus::PROCESSING,
                'payment_status'    => PaymentStatus::PENDING,
                'shipping_address'  => '753 Spruce St, Othertown, USA',
                'payment_method_id' => 2,
                'phone_number'      => '0198765433',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'user_id'           => 3,
                'promotion_id'      => 3,
                'total_amount'      => 250.00,
                'discount_amount'   => 35.00,
                'status'            => OrderStatus::PROCESSING,
                'payment_status'    => PaymentStatus::PENDING,
                'shipping_address'  => '258 Walnut St, Newtown, USA',
                'payment_method_id' => 1,
                'phone_number'      => '0154321987',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'user_id'           => 1,
                'promotion_id'      => 2,
                'total_amount'      => 90.00,
                'discount_amount'   => 10.00,
                'status'            => OrderStatus::PROCESSING,
                'payment_status'    => PaymentStatus::PENDING,
                'shipping_address'  => '369 Fir St, Anytown, USA',
                'payment_method_id' => 2,
                'phone_number'      => '0112233446',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'user_id'           => 2,
                'promotion_id'      => 1,
                'total_amount'      => 500.00,
                'discount_amount'   => 75.00,
                'status'            => OrderStatus::PROCESSING,
                'payment_status'    => PaymentStatus::PENDING,
                'shipping_address'  => '456 Oak St, Othertown, USA',
                'payment_method_id' => 1,
                'phone_number'      => '0123456780',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
        ];

        DB::table('orders')->insert($orders);
    }
}